# https://www.digitalocean.com/community/tutorials/how-to-use-traefik-as-a-reverse-proxy-for-docker-containers-on-ubuntu-16-04
# https://docs.traefik.io/getting-started/quick-start/
# https://docs.traefik.io/reference/static-configuration/file/
# https://docs.traefik.io/reference/dynamic-configuration/docker/


######################################################################################################
#
## docker network create --driver=bridge --subnet=172.21.0.0/16 --gateway=172.21.0.1 https-proxy
#
######################################################################################################

version: '3.5'

networks:
    proxy:
        external: true
        name: https-proxy

services:

  # docker run -d --restart=always --name=dnsmasq --network=https-proxy --cap-add=NET_ADMIN \
  #     -p 127.0.0.53:53:53/tcp -p 127.0.0.53:53:53/udp \
  #     -p 127.0.0.1:53:53/tcp -p 127.0.0.1:53:53/udp \
  #     -p $MYIP:53:53/tcp -p $MYIP:53:53/udp \
  #     andyshinn/dnsmasq:2.78 --address=/mio/$MYIP --server=8.8.8.8 --server=8.8.4.4
  dnsmasq: 
    image: andyshinn/dnsmasq:2.78
    restart: always
    command: 
      - "--address=/mio/$MYIP"
      - "--server=8.8.8.8" 
      - "--server=8.8.4.4"
    cap_add:
      - NET_ADMIN
    ports: 
      - "53:53/tcp"
      - "53:53/udp"

    networks:
      proxy:  {}

  reverse-proxy:
    image: traefik:v2.2   # The official v2 Traefik docker image
    restart: always
    
    # Enables the web UI and tells Traefik to listen to docker
    # We use configure file to set below params
    # command: 
        #- "--log.level=DEBUG"
        #- "--api.insecure=true"
        #- "--providers.docker=true"
        #- "--providers.docker.exposedbydefault=false"
        #- "--entrypoints.web.address=:80"
        #- "--entrypoints.websecure.address=:443"
        #- "--tls.stores.default.defaultCertificate.certFile=./cets/myKey.crt"
        #- "--tls.stores.default.defaultCertificate.keyFile=./certs/myKey.key"

    ports:
      - 80:80     # The HTTP port
      - 443:443   
      #- "8080:8080" # The Web UI (enabled by --api.insecure=true)
    
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./etc/traefik/:/etc/traefik/

    networks:
      proxy:  {}

  # whoami:
  #   image: containous/whoami
  #   restart: always
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.whoami.rule=Host(`whoami.dev.mio`)"
  #     - "traefik.http.routers.whoami.entrypoints=http"
  #     - "traefik.http.middlewares.whoami_https.redirectscheme.scheme=https"
  #     - "traefik.http.routers.whoami_https.rule=Host(`whoami.dev.mio`)"
  #     - "traefik.http.routers.whoami_https.entrypoints=https"
  #     - "traefik.http.routers.whoami_https.tls=true"
  #   networks:
  #     - proxy   


  