#!/bin/sh
set -e

if [ "$USER" = "root" ]; then
    # set localtime
    ln -sf /usr/share/zoneinfo/"$LOCALTIME" /etc/localtime

    # secure path
    chmod a-rwx -R "$PHP_INI_DIR"/conf.d/ /usr/local/etc/php-fpm.d/
fi

# Functions
set_conf() {
    echo "$4" >"$2"
    IFSO=$IFS
    IFS=$(echo -en "\n\b")
    for c in $(printenv | grep "$1"); do echo "$(echo "$c" | cut -d "=" -f1 | awk -F"$1" '{print $2}') $3 $(echo "$c" | cut -d "=" -f2)" >>"$2"; done
    IFS=$IFSO
}

# PHP
echo "date.timezone = \"${LOCALTIME}\"" >>"$PHP_INI_DIR"/conf.d/00-default.ini
if [ "$PHP_phpenmod" != "" ]; then docker-php-ext-enable "$PHP_phpenmod" >/dev/null 2>&1; fi

# Set php.ini
set_conf "PHP__" "$PHP_INI_DIR/conf.d/zz-user.ini" "="

# Make sure default php config has highest priority
if [ -f /usr/local/etc/php-fpm.d/www.conf ]; then
    mv /usr/local/etc/php-fpm.d/www.conf /usr/local/etc/php-fpm.d/00-www.conf
    mv /usr/local/etc/php-fpm.d/www.conf.default /usr/local/etc/php-fpm.d/00-www.conf.default
fi

# Set phpfpm.conf
# Set z0, z1, ... because there is a file named zz-docker.conf
set_conf "PHPFPM_GLOBAL__" "/usr/local/etc/php-fpm.d/z0-user-global.conf" "=" "[global]"
set_conf "PHPFPM__" "/usr/local/etc/php-fpm.d/z1-user-www.conf" "=" "[www]"

# Set msmtp server
if [ -n "$SMTP" ]; then
    echo 'sendmail_path = /usr/bin/msmtp -t' >>"$PHP_INI_DIR"/conf.d/00-default.ini
    echo -e "defaults \nauth           off \ntls            off \nlogfile        ~/.msmtp.log \naccount        mailcatcher \nhost           ${SMTP} \nport           ${SMTP_PORT:-25} \nauto_from on \naccount default : mailcatcher" >/etc/msmtprc
fi

# Run
exec "$@"
