############################################## 
# BUILD Command
#
# docker build -t testphpfpm - < Dockerfile2
#
##############################################


FROM 990863991647.dkr.ecr.us-west-2.amazonaws.com/devops/phpfpm:v7.2.6.2

ARG JUDY_VER=1.0.5

RUN set -xe apk add --no-cache gcc g++ make autoconf bsd-compat-headers

RUN curl -L -o /tmp/meminfo.tar.gz https://github.com/BitOne/php-meminfo/archive/master.tar.gz \
    && tar zxpf /tmp/meminfo.tar.gz -C /tmp \
    && rm -r /tmp/meminfo.tar.gz \
    && cd /tmp/php-meminfo-master/extension/php7/ && phpize && ./configure --enable-meminfo && make && make install \
	&& rm -rf /tmp/* \
    && docker-php-ext-enable meminfo 
	
RUN set -xe \
    && wget -O /tmp/judy.tar.gz http://downloads.sourceforge.net/project/judy/judy/Judy-${JUDY_VER}/Judy-${JUDY_VER}.tar.gz \
    && tar zxpf /tmp/judy.tar.gz -C /tmp \
    && cd /tmp/judy-${JUDY_VER} \
    && CFLAGS="-O2 -s" CXXFLAGS="-O2 -s" ./configure \
    && make \
    && make install 

RUN pecl channel-update pecl.php.net \
    && pecl install memprof \
    && docker-php-ext-enable memprof \
    && apk del autoconf gcc g++ bsd-compat-headers
    