version: '3.5'

#volumes:
    #    # this is for Native Linux (Ubuntu)
    #    appVolume:
    #        driver: local
    #        driver_opts:
    #            type: bind
    #            device: ${PROJECT_FOLDER}
    #            o: bind

    # this is for MacOS
    # appVolume:
    #     driver: local
    #     driver_opts:
    #         type: nfs
    #         o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
    #         device: ":/System/Volumes/Data/$PWD/data"

services:
  nifi:
    image: apache/nifi
    restart: on-failure
    ports:
        - 8080:8080
    environment: 
        - NIFI_WEB_HTTP_PORT=8080  
    volumes:
        - ./data/nifi_state:/opt/nifi/nifi-current/state
        - ./data/nifi_db:/opt/nifi/nifi-current/database_repository
        - ./data/nifi_flowfile:/opt/nifi/nifi-current/flowfile_repository
        - ./data/nifi_content:/opt/nifi/nifi-current/content_repository
        - ./data/nifi_provenance:/opt/nifi/nifi-current/provenance_repository   
        - ./data/work:/data
 