version: "3.5"

services:
    whoami:
        image: containous/whoami        
        container_name: whoami.dev.mio 
        volumes: 
            - .:/certs
        command: 
            --cert /certs/myKey.crt --key /certs/myKey.key    

    verifySSL:
        depends_on: 
            - whoami
        image: devops/trust-store
        build:
            context: .
            dockerfile: Dockerfile        
        command: openssl s_client -showcerts -servername whoami.dev.mio -connect whoami.dev.mio:80
            
